### ISSUE TITLE
Build: Missing templates from apps 

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#11]
https://github.com/andrewscwei/generator-vars-django/blob/master/app/templates/tasks/.taskconfig#L111

Templates in `project/apps` not included in build tasks.

**Comment by andrewscwei** [comment]
That is intended. This generator expects all templates to be inside `./app/templates` directory. If you need it to process templates outside of that directory, you'll have to create/modify your own task :)

**Comment by jakobadam** [comment]
OK. Thanks. I adjusted my own build file. 

What's the intention of not including them?

**Comment by andrewscwei** [comment]
The generator started out with Django 1.7 where by default templates were pointing to a single directory.
