### ISSUE TITLE
Watch on new images

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#9]
Is it possible make a watch for new images added, and process them, so they are available...

-- Jakob

**Comment by andrewscwei** [comment]
It appears that `gulp.watch()` has a history of not supporting watching added/deleted files: [http://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files](http://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files), but you can see that it seems to support it now if relative paths are provided. Give that a try.
